---

sudo: required
dist: trusty
language: python
python: "2.7"



env:

  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq



install:

  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi



script:

  # Check the 'common' role SYNTAX in playbook
  - ansible-playbook custom-setup.yml --syntax-check

  # Check the 'nodejs' role SYNTAX in playbook
  - ansible-playbook nodejs-setup.yml --syntax-check  

  # Check the 'docker' role SYNTAX in playbook
  - ansible-playbook docker-setup.yml --syntax-check    

  # Run the ansible-playbook to check 'common' ROLE
  - ansible-playbook custom-setup.yml --connection=local -v

  # Run the ansible-playbook to check 'nodejs' ROLE
  - ansible-playbook nodejs-setup.yml --connection=local -v

  # Run the ansible-playbook to check 'docker' ROLE
  #- ansible-playbook docker-setup.yml --connection=local -v

  

  # check LOCAL TIMEZONE is set to 'Europe/Amsterdam'
  - cat /etc/timezone | grep "Europe/Amsterdam" &>/dev/null && (echo "Timezone set to Europe_Amsterdam" && exit 0) || (echo "Timezone not set" && exit 1)
