---

sudo: required
dist: trusty
language: python
python: "2.7"
branches:
  only:
    - dev


services:
  - docker


before_install:
  - sudo apt-get update -qq
  - sudo docker pull saptadip/raspbian_base
  - sudo docker run -dt --name raspbianStage saptadip/raspbian_base /bin/bash sudo apt-get install ansible -y && ansible --version && git clone https://github.com/saptadip/ansible.git /tmp/testRepo && cd /tmp/testRepo && ansible-playbook custom-setup.yml --syntax-check
