---

sudo: required
dist: trusty
language: python
python: "2.7"
branches:
  only:
    - dev


services:
  - docker


before_install:
  - sudo apt-get update -qq
  - sudo docker pull saptadip/raspbian_base
  - sudo docker run --name ansible -d -it saptadip/raspbian_base
  - docker exec -it ansible git clone https://github.com/saptadip/ansible.git /tmp/testRepo && ansible-playbook /tmp/testRepo/custom-setup.yml --syntax-check
