---

sudo: required
dist: trusty
language: python
python: "2.7"
branches:
  only:
    - dev


services:
  - docker


before_install:
  - sudo docker pull williamyeh/ansible
  - sudo docker run -dt williamyeh/ansible /bin/bash git clone https://github.com/saptadip/ansible.git /tmp/testRepo && cd /tmp/testRepo && /tmp/ansible/bin/ansible-playbook custom-setup.yml --syntax-check
