---

sudo: required
dist: trusty
language: python
python: "2.7"
branches:
  only:
    - dev


services:
  - docker


before_install:
  - sudo apt-get update -qq
  - sudo docker pull resin/rpi-raspbian
  - sudo docker run -dt --name raspbianStage resin/rpi-raspbian /bin/bash apt-get install git ansible -y && git clone https://github.com/saptadip/ansible.git /tmp/testRepo && cd /tmp/testRepo && ansible-playbook custom-setup.yml --syntax-check
