---

# Set local timezone
#-------------------
- name: set timezone to CEST 
  timezone:
    name: {{ local_timezone }}
  notify:
    - restart cron


# Install OS utilities
#---------------------
- name: install dnsutils package
  apt:
    name: dnsutils
    state: present

- name: install vim package
  apt:
    name: vim
    state: present

- name: install git package
  apt:
    name: git
    state: present

- name: install tree package
  apt:
    name: tree
    state: present


# Install python packages
#------------------------
- name: install virtualenv for python
  pip:
    name: virtualenv


# Remove OS utilities
#--------------------
- name: remove wolfram-engine package
  apt:
    name: wolfram-engine
    state: absent	
    purge: yes
    autoremove: yes


# Run apt update cache
#---------------------
- name: update apt cache if it's 1 day old
  apt:
    update_cache: yes
    cache_valid_time: 86400 


# Set log rotation of ansible.log file
#-------------------------------------
- name: set log rotation of playbook exec log
  copy:
    src: ansible 
    dest: /etc/logrotate.d 
  notify:
    - run logrotate


# Customize bashrc file of 'pi' user
#-----------------------------------
# * Set history command to display date time format
- name: set profile for user pi
  remote_user: pi
  copy:
    src: .bashrc 
    dest: /home/pi

